import { createTheme, MantineTheme } from '@mantine/core';

import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import '@/assets/app.scss';
import '@/assets/scss/theme/index.scss';

export const theme = createTheme({
  fontFamily: 'var(--font-primary)',
  colors: {
    primary: [
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
      'var(--colors-primary)',
    ],
    secondary: [
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
      'var(--colors-secondary)',
    ],
    light: [
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
      'var(--colors-light)',
    ],
    dark: [
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
      'var(--colors-dark)',
    ],
    textPrimary: [
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
      'var(--colors-textPrimary)',
    ],
    textSecondary: [
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
      'var(--colors-textSecondary)',
    ],
    success: [
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
      'var(--colors-success)',
    ],
    warning: [
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
      'var(--colors-warning)',
    ],
    error: [
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
      'var(--colors-error)',
    ],
    gray: [
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
      'var(--colors-gray)',
    ],
    supportGray: [
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
      'var(--colors-supportGray)',
    ],
    silverGray: [
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
      'var(--colors-silverGray)',
    ],
    darkGray: [
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
      'var(--colors-darkGray)',
    ],
    lightGray: [
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
      'var(--colors-lightGray)',
    ],
    info: [
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
      'var(--colors-info)',
    ],
    accent: [
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
      'var(--colors-accent)',
    ],
  },
  spacing: {
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
  },
  components: {
    Input: {
      defaultProps: {
        size: 'md',
      },
      styles: (theme: MantineTheme) => ({
        wrapper: {
          '--input-bg': 'var(--input-bg)',
          '--input-border': 'var(--input-border)',
          '--input-text': 'var(--input-text)',
          '--input-placeholder-color': 'var(--input-placeholder)',
          '--input-disabled-bg': 'var(--input-disabledBg)',
          '--input-disabled-text': 'var(--input-disabledText)',
          '--input-error-border': 'var(--input-errorBorder)',
          '--input-error-text': 'var(--input-errorText)',
        },
        input: {
          backgroundColor: 'var(--input-bg)',
          borderColor: 'var(--input-border)',
          color: 'var(--input-text)',
          transition: 'border-color 0.2s ease',
          '&:hover': {
            borderColor: 'var(--input-borderHover)',
          },
          '&:focus': {
            borderColor: 'var(--input-borderFocus)',
          },
          '&::placeholder': {
            color: 'var(--input-placeholder)',
          },
          '&:disabled': {
            backgroundColor: 'var(--input-disabledBg)',
            color: 'var(--input-disabledText)',
            cursor: 'not-allowed',
          },
          '&[dataInvalid]': {
            borderColor: 'var(--input-errorBorder)',
            '&:focus': {
              borderColor: 'var(--input-errorBorder)',
            },
          },
        },
        label: {
          color: 'var(--input-text)',
          marginBottom: theme.spacing.xs,
        },
        error: {
          color: 'var(--input-errorText)',
          fontSize: '14px',
          marginTop: theme.spacing.xs,
        },
        required: {
          color: 'var(--input-errorText)',
        },
      }),
    },
    Button: {
      defaultProps: {
        size: 'md',
      },
    },
    Modal: {
      defaultProps: {
        size: 'lg',
      },
    },
  },
  other: {
    input: {
      backgroundColor: 'var(--input-bg)',
      borderColor: 'var(--input-border)',
      textColor: 'var(--input-text)',
      placeholderColor: 'var(--input-placeholder)',
      disabledBackgroundColor: 'var(--input-disabledBg)',
      disabledTextColor: 'var(--input-disabledText)',
      errorBorderColor: 'var(--input-errorBorder)',
      errorTextColor: 'var(--input-errorText)',
    },
  },
});
